version: '3.1'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: lisenet/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - /docker/openvpn/conf:/etc/openvpn
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 128M
networks:
  default:
      external: true
      name: vpn-net

